# Generated by Django 2.2.6 on 2019-10-09 14:38

from django.db import migrations, models
import django.db.models.deletion
import mainApp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vincode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Make', models.CharField(max_length=150)),
                ('Model', models.CharField(max_length=150)),
                ('Color', models.CharField(max_length=150)),
                ('Engine', models.CharField(max_length=150)),
                ('Condition', models.CharField(max_length=150)),
                ('Primary_damage', models.CharField(max_length=150)),
                ('Secondary_damage', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=mainApp.models.get_image_filename, verbose_name='Image')),
                ('vincode', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mainApp.Vincode')),
            ],
        ),
    ]
