# Generated by Django 2.2.6 on 2019-10-09 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0004_auto_20191009_1453'),
    ]

    operations = [
        migrations.AddField(
            model_name='vincode',
            name='vincode_key',
            field=models.CharField(default='', max_length=20),
        ),
    ]
